export { default as SDBody } from './comps/sd-body'
export { default as SDText } from './comps/sd-elip'
export { default as SDLoading } from './comps/sd-loading'
export { default as SDSlide } from './comps/sd-slide'
export { default as SDPopup } from './comps/sd-popup'
export { default as SDQuantity } from './comps/sd-quantity'
